// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.3
// source: publicdata.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取临时上传连接请求
type GetCacheURLReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCacheURLReq) Reset() {
	*x = GetCacheURLReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicdata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheURLReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheURLReq) ProtoMessage() {}

func (x *GetCacheURLReq) ProtoReflect() protoreflect.Message {
	mi := &file_publicdata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheURLReq.ProtoReflect.Descriptor instead.
func (*GetCacheURLReq) Descriptor() ([]byte, []int) {
	return file_publicdata_proto_rawDescGZIP(), []int{0}
}

// 获取临时上传连接响应
type GetCacheURLResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// 状态码 0成功，其他失败
	Code int32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// 提示信息
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *GetCacheURLResp) Reset() {
	*x = GetCacheURLResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_publicdata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCacheURLResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCacheURLResp) ProtoMessage() {}

func (x *GetCacheURLResp) ProtoReflect() protoreflect.Message {
	mi := &file_publicdata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCacheURLResp.ProtoReflect.Descriptor instead.
func (*GetCacheURLResp) Descriptor() ([]byte, []int) {
	return file_publicdata_proto_rawDescGZIP(), []int{1}
}

func (x *GetCacheURLResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCacheURLResp) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_publicdata_proto protoreflect.FileDescriptor

var file_publicdata_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x10, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x43, 0x61,
	0x63, 0x68, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x22, 0x37, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x32, 0x6f, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x61, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x52, 0x4c, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x55, 0x52, 0x4c, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x63, 0x68, 0x65, 0x55, 0x52, 0x4c, 0x52, 0x65, 0x73, 0x70, 0x22, 0x23,
	0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1d, 0x12, 0x1b, 0x2f, 0x32, 0x34, 0x37, 0x31, 0x30, 0x2f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x63, 0x61, 0x63, 0x68, 0x65, 0x5f,
	0x75, 0x72, 0x6c, 0x42, 0x1b, 0x5a, 0x19, 0x79, 0x69, 0x62, 0x61, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2f, 0x6d, 0x79, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_publicdata_proto_rawDescOnce sync.Once
	file_publicdata_proto_rawDescData = file_publicdata_proto_rawDesc
)

func file_publicdata_proto_rawDescGZIP() []byte {
	file_publicdata_proto_rawDescOnce.Do(func() {
		file_publicdata_proto_rawDescData = protoimpl.X.CompressGZIP(file_publicdata_proto_rawDescData)
	})
	return file_publicdata_proto_rawDescData
}

var file_publicdata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_publicdata_proto_goTypes = []interface{}{
	(*GetCacheURLReq)(nil),  // 0: proto.GetCacheURLReq
	(*GetCacheURLResp)(nil), // 1: proto.GetCacheURLResp
}
var file_publicdata_proto_depIdxs = []int32{
	0, // 0: proto.Publicdata.GetCacheURL:input_type -> proto.GetCacheURLReq
	1, // 1: proto.Publicdata.GetCacheURL:output_type -> proto.GetCacheURLResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_publicdata_proto_init() }
func file_publicdata_proto_init() {
	if File_publicdata_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_publicdata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCacheURLReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_publicdata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCacheURLResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_publicdata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publicdata_proto_goTypes,
		DependencyIndexes: file_publicdata_proto_depIdxs,
		MessageInfos:      file_publicdata_proto_msgTypes,
	}.Build()
	File_publicdata_proto = out.File
	file_publicdata_proto_rawDesc = nil
	file_publicdata_proto_goTypes = nil
	file_publicdata_proto_depIdxs = nil
}
