// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: publicdata.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Publicdata_GetCacheURL_FullMethodName = "/proto.Publicdata/GetCacheURL"
)

// PublicdataClient is the client API for Publicdata service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicdataClient interface {
	// GetCacheURL 获取临时上传连接
	GetCacheURL(ctx context.Context, in *GetCacheURLReq, opts ...grpc.CallOption) (*GetCacheURLResp, error)
}

type publicdataClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicdataClient(cc grpc.ClientConnInterface) PublicdataClient {
	return &publicdataClient{cc}
}

func (c *publicdataClient) GetCacheURL(ctx context.Context, in *GetCacheURLReq, opts ...grpc.CallOption) (*GetCacheURLResp, error) {
	out := new(GetCacheURLResp)
	err := c.cc.Invoke(ctx, Publicdata_GetCacheURL_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicdataServer is the server API for Publicdata service.
// All implementations must embed UnimplementedPublicdataServer
// for forward compatibility
type PublicdataServer interface {
	// GetCacheURL 获取临时上传连接
	GetCacheURL(context.Context, *GetCacheURLReq) (*GetCacheURLResp, error)
	mustEmbedUnimplementedPublicdataServer()
}

// UnimplementedPublicdataServer must be embedded to have forward compatible implementations.
type UnimplementedPublicdataServer struct {
}

func (UnimplementedPublicdataServer) GetCacheURL(context.Context, *GetCacheURLReq) (*GetCacheURLResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCacheURL not implemented")
}
func (UnimplementedPublicdataServer) mustEmbedUnimplementedPublicdataServer() {}

// UnsafePublicdataServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicdataServer will
// result in compilation errors.
type UnsafePublicdataServer interface {
	mustEmbedUnimplementedPublicdataServer()
}

func RegisterPublicdataServer(s grpc.ServiceRegistrar, srv PublicdataServer) {
	s.RegisterService(&Publicdata_ServiceDesc, srv)
}

func _Publicdata_GetCacheURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCacheURLReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicdataServer).GetCacheURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Publicdata_GetCacheURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicdataServer).GetCacheURL(ctx, req.(*GetCacheURLReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Publicdata_ServiceDesc is the grpc.ServiceDesc for Publicdata service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Publicdata_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Publicdata",
	HandlerType: (*PublicdataServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCacheURL",
			Handler:    _Publicdata_GetCacheURL_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publicdata.proto",
}
