// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: sensor.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sensor_SensorPost_FullMethodName = "/proto.Sensor/SensorPost"
)

// SensorClient is the client API for Sensor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorClient interface {
	// SensorPost 流式测试
	SensorPost(ctx context.Context, opts ...grpc.CallOption) (Sensor_SensorPostClient, error)
}

type sensorClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorClient(cc grpc.ClientConnInterface) SensorClient {
	return &sensorClient{cc}
}

func (c *sensorClient) SensorPost(ctx context.Context, opts ...grpc.CallOption) (Sensor_SensorPostClient, error) {
	stream, err := c.cc.NewStream(ctx, &Sensor_ServiceDesc.Streams[0], Sensor_SensorPost_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorSensorPostClient{stream}
	return x, nil
}

type Sensor_SensorPostClient interface {
	Send(*SensorPostReq) error
	Recv() (*SensorPostResp, error)
	grpc.ClientStream
}

type sensorSensorPostClient struct {
	grpc.ClientStream
}

func (x *sensorSensorPostClient) Send(m *SensorPostReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorSensorPostClient) Recv() (*SensorPostResp, error) {
	m := new(SensorPostResp)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorServer is the server API for Sensor service.
// All implementations must embed UnimplementedSensorServer
// for forward compatibility
type SensorServer interface {
	// SensorPost 流式测试
	SensorPost(Sensor_SensorPostServer) error
	mustEmbedUnimplementedSensorServer()
}

// UnimplementedSensorServer must be embedded to have forward compatible implementations.
type UnimplementedSensorServer struct {
}

func (UnimplementedSensorServer) SensorPost(Sensor_SensorPostServer) error {
	return status.Errorf(codes.Unimplemented, "method SensorPost not implemented")
}
func (UnimplementedSensorServer) mustEmbedUnimplementedSensorServer() {}

// UnsafeSensorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorServer will
// result in compilation errors.
type UnsafeSensorServer interface {
	mustEmbedUnimplementedSensorServer()
}

func RegisterSensorServer(s grpc.ServiceRegistrar, srv SensorServer) {
	s.RegisterService(&Sensor_ServiceDesc, srv)
}

func _Sensor_SensorPost_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorServer).SensorPost(&sensorSensorPostServer{stream})
}

type Sensor_SensorPostServer interface {
	Send(*SensorPostResp) error
	Recv() (*SensorPostReq, error)
	grpc.ServerStream
}

type sensorSensorPostServer struct {
	grpc.ServerStream
}

func (x *sensorSensorPostServer) Send(m *SensorPostResp) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorSensorPostServer) Recv() (*SensorPostReq, error) {
	m := new(SensorPostReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Sensor_ServiceDesc is the grpc.ServiceDesc for Sensor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sensor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Sensor",
	HandlerType: (*SensorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SensorPost",
			Handler:       _Sensor_SensorPost_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "sensor.proto",
}
