// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Stream_BiDiStream_FullMethodName   = "/proto.Stream/BiDiStream"
	Stream_ClientStream_FullMethodName = "/proto.Stream/ClientStream"
	Stream_UniStream_FullMethodName    = "/proto.Stream/UniStream"
)

// StreamClient is the client API for Stream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StreamClient interface {
	// 双向流式RPC
	BiDiStream(ctx context.Context, opts ...grpc.CallOption) (Stream_BiDiStreamClient, error)
	// 客户端流式RPC
	ClientStream(ctx context.Context, opts ...grpc.CallOption) (Stream_ClientStreamClient, error)
	// 服务端流式RPC
	UniStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Stream_UniStreamClient, error)
}

type streamClient struct {
	cc grpc.ClientConnInterface
}

func NewStreamClient(cc grpc.ClientConnInterface) StreamClient {
	return &streamClient{cc}
}

func (c *streamClient) BiDiStream(ctx context.Context, opts ...grpc.CallOption) (Stream_BiDiStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[0], Stream_BiDiStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamBiDiStreamClient{stream}
	return x, nil
}

type Stream_BiDiStreamClient interface {
	Send(*StreamRequest) error
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type streamBiDiStreamClient struct {
	grpc.ClientStream
}

func (x *streamBiDiStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamBiDiStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) ClientStream(ctx context.Context, opts ...grpc.CallOption) (Stream_ClientStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[1], Stream_ClientStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamClientStreamClient{stream}
	return x, nil
}

type Stream_ClientStreamClient interface {
	Send(*StreamRequest) error
	CloseAndRecv() (*StreamResponse, error)
	grpc.ClientStream
}

type streamClientStreamClient struct {
	grpc.ClientStream
}

func (x *streamClientStreamClient) Send(m *StreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *streamClientStreamClient) CloseAndRecv() (*StreamResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *streamClient) UniStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Stream_UniStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Stream_ServiceDesc.Streams[2], Stream_UniStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &streamUniStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Stream_UniStreamClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type streamUniStreamClient struct {
	grpc.ClientStream
}

func (x *streamUniStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// StreamServer is the server API for Stream service.
// All implementations must embed UnimplementedStreamServer
// for forward compatibility
type StreamServer interface {
	// 双向流式RPC
	BiDiStream(Stream_BiDiStreamServer) error
	// 客户端流式RPC
	ClientStream(Stream_ClientStreamServer) error
	// 服务端流式RPC
	UniStream(*StreamRequest, Stream_UniStreamServer) error
	mustEmbedUnimplementedStreamServer()
}

// UnimplementedStreamServer must be embedded to have forward compatible implementations.
type UnimplementedStreamServer struct {
}

func (UnimplementedStreamServer) BiDiStream(Stream_BiDiStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method BiDiStream not implemented")
}
func (UnimplementedStreamServer) ClientStream(Stream_ClientStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ClientStream not implemented")
}
func (UnimplementedStreamServer) UniStream(*StreamRequest, Stream_UniStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UniStream not implemented")
}
func (UnimplementedStreamServer) mustEmbedUnimplementedStreamServer() {}

// UnsafeStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StreamServer will
// result in compilation errors.
type UnsafeStreamServer interface {
	mustEmbedUnimplementedStreamServer()
}

func RegisterStreamServer(s grpc.ServiceRegistrar, srv StreamServer) {
	s.RegisterService(&Stream_ServiceDesc, srv)
}

func _Stream_BiDiStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).BiDiStream(&streamBiDiStreamServer{stream})
}

type Stream_BiDiStreamServer interface {
	Send(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type streamBiDiStreamServer struct {
	grpc.ServerStream
}

func (x *streamBiDiStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamBiDiStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_ClientStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StreamServer).ClientStream(&streamClientStreamServer{stream})
}

type Stream_ClientStreamServer interface {
	SendAndClose(*StreamResponse) error
	Recv() (*StreamRequest, error)
	grpc.ServerStream
}

type streamClientStreamServer struct {
	grpc.ServerStream
}

func (x *streamClientStreamServer) SendAndClose(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *streamClientStreamServer) Recv() (*StreamRequest, error) {
	m := new(StreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Stream_UniStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StreamServer).UniStream(m, &streamUniStreamServer{stream})
}

type Stream_UniStreamServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type streamUniStreamServer struct {
	grpc.ServerStream
}

func (x *streamUniStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Stream_ServiceDesc is the grpc.ServiceDesc for Stream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Stream",
	HandlerType: (*StreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BiDiStream",
			Handler:       _Stream_BiDiStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "ClientStream",
			Handler:       _Stream_ClientStream_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UniStream",
			Handler:       _Stream_UniStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "stream.proto",
}
